import { Palette } from "../globals.slint";
import { DragBar } from "drag-bar.slint";

export component Popup {
    out property <bool> is-open <=> popup.is-open;
    in-out property <string> title;
    in-out property <string> btn-text: "OK";
    in property <length> h_scaling:-200px;
    in property <bool> second-btn:false;
    // in property <length> height;
    public function toggle-popup() {
        popup.is-open ? popup.close() : popup.show();
    }

    callback start-drag();
    callback minimize-app();
    callback close-app();

    callback second-btn-close();
    callback closing();

    popup := PopupWindow {
        close-policy: close-on-click-outside;
        height: parent.height;
        width: parent.width;
        Rectangle {
            background: is-open ? #000000.with-alpha(0.45) : #000000.with-alpha(0);

            animate background {
                easing: ease-in-out;
                duration: 150ms;
            }
            HorizontalLayout {
                z: 67;
                DragBar {
                    start-drag => start-drag();
                    close-app => close-app();
                    minimize-app => minimize-app();
                }
            }

            Rectangle {
                height: parent.height + h_scaling;
                width: parent.width / 4;
                drop-shadow-offset-x: 2px;
                drop-shadow-offset-y: 2px;
                drop-shadow-blur: 4px;
                drop-shadow-spread: 1px;
                drop-shadow-color: black;
                border-width: 2px;
                border-color: #09090b;
                border-radius: 8px;
                background: #202023;
                opacity: is-open ? 100% : 0;
                animate opacity {
                    easing: ease-in-out;
                    duration: 150ms;
                }

                VerticalLayout {
                    padding-left: 16px;
                    padding-right: 16px;
                    padding-bottom: 12px;

                    alignment: space-between;

                    @children

                    HorizontalLayout {
                        spacing: 8px;
                        if root.second-btn: Rectangle {
                            first-btn := TouchArea {
                                clicked => {
                                    popup.close();
                                }

                                pointer-event(event) => {
                                    if (event.button == PointerEventButton.right && event.kind == PointerEventKind.up) {
                                        second-btn-close();
                                        popup.close();
                                    }
                                }
                                mouse-cursor: pointer;
                            }

                            width: parent.width / 2 -8px;
                            border-radius: 8px;
                            border-width: 1px;
                            background: first-btn.has-hover ? rgba(255, 32, 86, 100%) : rgba(255, 32, 86, 84%);
                            border-color: rgb(259,99,126);


                            animate background, border-color {
                                easing: ease-in-out;
                                duration: 150ms;
                            }
                            VerticalLayout {
                                padding-top: 8px;
                                padding-bottom: 8px;
                                alignment: center;
                                cross-axis-alignment: center;
                                Text {
                                    text: "Dismiss";
                                    color: white;
                                    font-weight: FontWeight.bold;
                                    font-family: "Inter";
                                    font-size: 1.5rem;
                                }
                            }
                        }
                        Rectangle {
                            second-btn := TouchArea {
                                clicked => {
                                    popup.close();
                                    closing()
                                }
                                mouse-cursor: pointer;
                            }

                            width: root.second-btn ? parent.width / 2 -8px : parent.width;
                            border-radius: 8px;
                            border-width: 1px;
                            background: second-btn.has-hover ? rgba(255, 32, 86, 100%) : rgba(255, 32, 86, 84%);
                            border-color: rgb(259,99,126);


                            animate background, border-color {
                                easing: ease-in-out;
                                duration: 150ms;
                            }
                            VerticalLayout {
                                padding-top: 8px;
                                padding-bottom: 8px;
                                alignment: center;
                                cross-axis-alignment: center;
                                Text {
                                    text: btn-text;
                                    color: white;
                                    font-weight: FontWeight.bold;
                                    font-family: "Inter";
                                    font-size: 1.5rem;
                                }
                            }
                        }
                    }

                }
            }
        }
    }
}
