import {
    ScrollView,
    Switch,
} from "std-widgets.slint";
import "./assets/fonts/Outfit-VariableFont_wght.ttf";
import "./assets/fonts/Inter-VariableFont_opsz,wght.ttf";
import "./assets/fonts/0xProto-Regular.ttf";
import { PlayButtonSVGIcon } from "./assets/icons/command/play.slint";
import { StopButtonSVGIcon } from"./assets/icons/command/stop.slint";
import { Popup } from "./components/popup.slint";
import { Palette, Config } from "./globals.slint";
import { RightToggle, Toggle } from "./components/toggle.slint";
import { LinkEntry } from "./components/link-entry.slint";
import { DragBar } from "components/drag-bar.slint";

export enum ProxyState { idle, updating, starting, running }
export { Config }
export component LogsWindow inherits Window {
    in-out property <string> logs: "";
    preferred-width: 1160px;
    preferred-height: 646px;
    title: "Lilith Logs";
    public function update-logs(new: string) {
        logs = logs + new + "\n";
        if (auto-scroll-toggle.selected) {
            logs_view.viewport-y = min(0px, - logs_view.viewport-height + logs_view.visible-height);
        }
    }

    Image {
        source: @image-url("./assets/BackgroundImage.png");
        width: 100%;
        height: 100%;
        image-fit: ImageFit.cover;
    }

    Rectangle {
        height: 80%;
        width: 90%;
        drop-shadow-offset-x: 2px;
        drop-shadow-offset-y: 2px;
        drop-shadow-blur: 4px;
        drop-shadow-spread: 1px;
        drop-shadow-color: black;
        border-width: 2px;
        border-color: #09090b;
        border-radius: 8px;
        background: #101013;
        VerticalLayout {
            padding-right: 8px;
            padding-left: 8px;
            padding-bottom: 8px;
            logs_view := ScrollView {
                HorizontalLayout {
                    alignment: start;

                    Text {
                        font-family: "0xProto";
                        text: logs;
                        color: #d4d4d4;
                    }
                }
            }

            auto-scroll-toggle := RightToggle {
                name: "Auto-Scroll";
                Rectangle { }
            }
        }
    }
}



export component AppWindow inherits Window {

    property <length> win_width: 1160px;
    property <length> win_height: 646px;

    in-out property <int> counter: 0;
    in-out property <ProxyState> proxy-state: idle;
    in-out property <string> status-text;

    width: win_width;
    height: win_height;

    no-frame: true;
    callback start-drag();

    callback request-increase-value();

    callback big-button-clicked();

    callback show-logs-window();

    callback config-popup-closed <=> config-popup.closing;

    callback close-app();
    callback minimize-app();

    public function toggle-error-popup() {
        error-popup.toggle-popup();
    }

    public function toggle-config-popup() {
        config-popup.toggle-popup();
    }

    in-out property <string> error-popup-title: "ANNOUNCEMENT";
    in-out property <styled-text> error-popup-body: @markdown("i love cats they are so cute and fluffy x3");

    Image {
        source: @image-url("./assets/BackgroundImage.png");
        width: win_width;
        height: win_height;
    }

    HorizontalLayout {
        z: 67;
        DragBar {
            start-drag => start-drag();
            close-app => close-app();
            minimize-app => minimize-app();
        }
    }

    error-popup := Popup {
        height: win_height;
        width: win_width;
        start-drag => start-drag();
        close-app => close-app();
        minimize-app => minimize-app();

        VerticalLayout {
            alignment: center;
            padding-top: 32px;
            cross-axis-alignment: start;
            Text {
                text: error-popup-title;
                color: white;
                font-family: "Inter";
                font-size: 2rem;
                font-weight: FontWeight.black;
            }

            Rectangle {
                height: 10px;
            }

            StyledText {
                text: error-popup-body;
                default-font-size: 1.25rem;
                default-color: #d4d4d4;
                default-font-family: "Inter";
            }
        }
    }

    config-popup := Popup {
        height: win_height;
        width: win_width;
        start-drag => start-drag();
        close-app => close-app();
        minimize-app => minimize-app();
        btn-text: "Save";
        VerticalLayout {
            alignment: start;
            padding-top: 32px;
            HorizontalLayout {
                cross-axis-alignment: center;
                alignment: center;
                Text {
                    text: "Configuration";
                    color: white;
                    font-family: "Inter";
                    horizontal-alignment: center;
                    font-size: 2rem;
                    font-weight: FontWeight.black;
                }
            }

            Rectangle {
                height: 10px;
            }

            VerticalLayout {
                cross-axis-alignment: start;
                spacing: 8px;
                beta-toggle := Toggle {
                    name: "Beta";
                    selected <=> Config.alpha;
                }

                deub-toggle := Toggle {
                    name: "Debug";
                    selected <=> Config.debug;
                }
            }
        }
    }

    VerticalLayout {

        alignment: center;
        padding-left: 8rem;
        HorizontalLayout {
            padding: 0px;
            alignment: start;
            cross-axis-alignment: end;

            Image {
                TouchArea {
                    double-clicked => { toggle-config-popup() }
                }

                horizontal-alignment: left;
                source: @image-url("./assets/LilithLogo.png");
                width: 310px;
            }
        }

        Rectangle {
            private property <bool> active: proxy-state == ProxyState.idle || proxy-state == ProxyState.running;
            launch-btn := TouchArea {
                mouse-cursor: active ? pointer : not-allowed;
                clicked => {
                    big-button-clicked();
                };
            }

            border-color: proxy-state == ProxyState.idle ? rgb(259,99,126) : rgb(161,161,161);
            border-width: 1px;
            border-radius: 8px;
            background: {
                if (proxy-state == ProxyState.idle) {
                    return launch-btn.has-hover ? rgba(255, 32, 86, 100%) : rgba(255, 32, 86, 84%);
                } else {
                    return rgb(115,115,115);
                }
            };
            width: 186px;
            height: 50px;

            transform-scale: (!active ? 0 : (!launch-btn.has-hover ? 0 : proxy-state == ProxyState.idle ? 3% : -8%)) + 100%;
            animate background, width, transform-scale {
                duration: 300ms;
                easing: ease-in-out;
            }

            HorizontalLayout {
                padding-right: 0.5rem;
                padding-left: 0.5rem;
                alignment: center;
                spacing: 8px;

                VerticalLayout {
                    alignment: center;

                    Text {
                        font-size: 2rem;
                        color: white;
                        text: {
                            if (proxy-state == ProxyState.starting) {
                                return "Starting";
                            }
                            if (proxy-state == ProxyState.running) {
                                return "Stop";
                            }
                            if (proxy-state == ProxyState.updating) {
                                return "Updating";
                            }
                            return "Launch";
                        };
                        font-family: "Inter";
                        font-weight: FontWeight.black;
                    }
                }

                if proxy-state == ProxyState.idle || proxy-state == ProxyState.running: VerticalLayout {
                    alignment: center;
                    if proxy-state == ProxyState.idle: PlayButtonSVGIcon { }

                    if proxy-state == ProxyState.running: StopButtonSVGIcon { }
                }
            }
        }

        VerticalLayout {
            padding-top: 1rem;
            spacing: 2px;
            LinkEntry {
                text: "Documentation";
                clicked => {
                    Platform.open-url("https://docs.lilith.rip");
                }
                icon: @image-url("./assets/icons/lucide/docs.svg");
            }

            LinkEntry {
                text: "Changelog";
                clicked => {
                    Platform.open-url("https://github.com/lilithmod/releases/releases\{Config.alpha ? "" : "/latest"} ");
                }
                icon: @image-url("./assets/icons/lucide/rocket.svg");
            }

            LinkEntry {
                text: "Settings";
                clicked => {
                    Platform.open-url("https://me.lilith.rip\{Config.alpha ? "/beta" : ""} ");
                }
                icon: @image-url("./assets/icons/lucide/settings.svg");
            }

            LinkEntry {
                visible: proxy-state == ProxyState.running;
                text: "Logs";
                clicked => show-logs-window();
                icon: @image-url("./assets/icons/lucide/logs.svg");
            }
        }
    }

    Text {
        text: status-text;
        color: #737373;
        font-size: 1rem;
        x: 0;
        y: 00;
    }
}
